# GitHub Actions docs
# https://help.github.com/en/articles/about-github-actions
# https://help.github.com/en/articles/workflow-syntax-for-github-actions

name: Install Dependencies, Lint, Build and Test

on: [push]

jobs:
  test:
    name: Test on node ${{ matrix.node_version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node_version: [14]
        os: [macOS-latest]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node_version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node_version }}
    - name: Install Dependencies
      run: npm ci
    - name: Install Ionic CLI
      run: npm install -g @ionic/cli native-run cordova-res
   # - name: Install Capacitor
   #   run: npm install @capacitor/camera @capacitor/storage @capacitor/filesystem
   # - name: Install PWA Components
   #   run: npm install @ionic/pwa-elements
    - name: Lint
      run: npm run lint -- --fix
    - name: Ionic Build
      run: npm run ionicBuild
    - uses: actions/upload-artifact@v2
      with:
        name: my-artifact
        path: www/ # or path/to/artifact
  #  - name: Add IOS Capacitor
  #    run: npm run addIOS
  #  - name: Add Android Capacitor
  #    run: npm run addAndroid
  #  - name: Test
  #    run: npm test
